In [1]:
# import string
import pandas as pd

In [2]:
# alphabet = string.ascii_lowercase

In [3]:
# for letter in alphabet:
#   ufc_stats = f'http://ufcstats.com/statistics/fighters?char={letter}&page=all'
#   if letter == 'a':
#     df = pd.read_html(ufc_stats)[0]
#   else:
#     temp_df = pd.read_html(ufc_stats)[0]
#     df = pd.concat([df, temp_df])

In [4]:
ufc_stats = 'http://ufcstats.com/statistics/fighters?char=*&page=all'
df = pd.read_html(ufc_stats)[0]

In [5]:
df.reset_index(drop=True, inplace=True)

In [6]:
df

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,W,L,D,Belt
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tom,Aaron,NaN,--,155 lbs.,--,NaN,5.0,3.0,0.0,NaN
2,Danny,Abbadi,The Assassin,"5' 11""",155 lbs.,--,Orthodox,4.0,6.0,0.0,NaN
3,Nariman,Abbasov,NaN,"5' 8""",155 lbs.,--,NaN,27.0,3.0,0.0,NaN
4,David,Abbott,Tank,"6' 0""",265 lbs.,--,Switch,10.0,15.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3872,Dave,Zitanick,NaN,--,170 lbs.,--,NaN,5.0,7.0,0.0,NaN
3873,Alex,Zuniga,NaN,--,145 lbs.,--,NaN,6.0,3.0,0.0,NaN
3874,George,Zuniga,NaN,"5' 9""",185 lbs.,--,NaN,3.0,1.0,0.0,NaN
3875,Allan,Zuniga,Tigre,"5' 7""",155 lbs.,"70.0""",Orthodox,13.0,1.0,0.0,NaN
3876,Virgil,Zwicker,RezDog,"6' 2""",205 lbs.,"74.0""",NaN,15.0,6.0,1.0,NaN

In [7]:
df.to_csv('1_ufc_fighters_scraped.csv', index=False)